# Generated by Django 5.1.15 on 2026-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=150)),
                ('exercise_id', models.CharField(max_length=50)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.TextField()),
                ('response_status', models.IntegerField()),
                ('is_exploited', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPIScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=150, unique=True)),
                ('kpi_1_transfer_score', models.FloatField(default=84.0)),
                ('kpi_2_completion_rate', models.FloatField(default=88.0)),
                ('kpi_3_realism_rating', models.FloatField(default=86.0)),
                ('kpi_4_unsafe_outcomes', models.IntegerField(default=0)),
                ('kpi_5_attack_detection', models.FloatField(default=94.2)),
                ('kpi_6_false_positive', models.FloatField(default=1.8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
