# Generated by Django 5.1.15 on 2026-08-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralSecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_email', models.CharField(max_length=150)),
                ('target_resource', models.CharField(blank=True, max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('result', models.CharField(default='SUCCESS', max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=150)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=150)),
                ('target_user_email', models.CharField(max_length=150)),
                ('old_role', models.CharField(max_length=50)),
                ('new_role', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, default='Administrative Role Assignment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='requires_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
