# Generated by Django 5.1.15 on 2026-08-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_centralsecuritylog_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralsecuritylog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='centralsecuritylog',
            name='event_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='centralsecuritylog',
            name='target_resource',
            field=models.CharField(max_length=255),
        ),
    ]
