# Generated by Django 5.1.15 on 2026-08-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(max_length=64, unique=True)),
                ('student_email', models.CharField(max_length=150)),
                ('assessor_email', models.CharField(blank=True, max_length=150)),
                ('target_api_name', models.CharField(default='Unfamiliar Target API (FinTech Gateway)', max_length=150)),
                ('status', models.CharField(default='SUBMITTED', max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('technique_transfer_score', models.IntegerField(default=85)),
                ('exercise_completion_score', models.IntegerField(default=90)),
                ('realism_assessment_score', models.IntegerField(default=88)),
                ('unsafe_outcomes_count', models.IntegerField(default=0)),
                ('attack_path_detection_rate', models.FloatField(default=95.0)),
                ('false_positive_rate', models.FloatField(default=2.5)),
                ('evidence_notes', models.TextField(blank=True)),
                ('assessor_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
