# Generated by Django 5.1.15 on 2026-08-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('owasp_code', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('estimated_time', models.CharField(max_length=20)),
                ('scenario_description', models.TextField()),
                ('learning_objective', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=150)),
                ('module_id', models.CharField(max_length=50)),
                ('hint_level', models.IntegerField(default=1)),
                ('kpi_penalty', models.FloatField(default=10.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
