# Generated by Django 5.1.15 on 2026-08-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guided_exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=150)),
                ('exercise_id', models.CharField(max_length=50)),
                ('exercise_title', models.CharField(max_length=200)),
                ('status', models.CharField(default='NOT_STARTED', max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('hints_used', models.IntegerField(default=0)),
                ('time_spent', models.CharField(default='12m', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('user_email', 'exercise_id')},
            },
        ),
    ]
