# Generated by Django 5.1.15 on 2026-08-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guided_exercises', '0002_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLabSession',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.CharField(max_length=150)),
                ('exercise_id', models.CharField(max_length=50)),
                ('container_name', models.CharField(max_length=150)),
                ('assigned_port', models.IntegerField()),
                ('session_token', models.CharField(max_length=100)),
                ('status', models.CharField(default='RUNNING', max_length=30)),
                ('test_results', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
