# Generated by Django 5.1.15 on 2026-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guided_exercises', '0003_userlabsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlabsession',
            name='accumulated_paused_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlabsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlabsession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlabsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
