# Generated by Django 5.1.15 on 2026-08-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guided_exercises', '0004_userlabsession_accumulated_paused_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=150)),
                ('exercise_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='SUBMITTED', max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('request_payload', models.TextField(blank=True)),
                ('evidence_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
