# Generated by Django 5.1.15 on 2026-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('owasp_category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('port', models.IntegerField(default=8000)),
                ('last_health_check', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuardrailTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('expected_behavior', models.TextField(blank=True)),
                ('recovery_time', models.CharField(default='0.12s', max_length=20)),
                ('status', models.CharField(default='PASS', max_length=20)),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('exercise_name', models.CharField(max_length=150)),
                ('request_payload', models.TextField(blank=True)),
                ('response_status', models.IntegerField(default=200)),
                ('status', models.CharField(default='Pending Review', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ValidationItem',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='deployed_set',
        ),
        migrations.AddField(
            model_name='cohort',
            name='active_exercise_set',
            field=models.CharField(default='OWASP API Top 10 Baseline', max_length=100),
        ),
        migrations.AddField(
            model_name='cohort',
            name='code',
            field=models.CharField(default='COH-001', max_length=20),
        ),
        migrations.AddField(
            model_name='cohort',
            name='deployed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
