# Generated by Django 5.1.15 on 2026-08-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0002_containerfixture_guardrailtestrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=150)),
                ('target_user_email', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('affected_session', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
