# Generated by Django 5.1.15 on 2026-08-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_email', models.CharField(max_length=150)),
                ('student_email', models.CharField(max_length=150)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('instructor_email', 'student_email')},
            },
        ),
    ]
